# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tags:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Indicate tags to run'
        # Default value if no value is explicitly provided
        default: 'smoke'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run:  mvn -B verify -Dcucumber.filter.tags="@${{ github.event.inputs.tags }}" --file pom.xml 
    - name: Archive Cucumber results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: target/site/serenity/
        retention-days: 3
